---
- name: Install PHP with dependencies
  apt: "pkg={{ item }} state=present"
  environment:
    LC_CTYPE: en_US.UTF-8
  with_items: blackroom_php_packages
  tags: build

- name: Configure PHP
  lineinfile: "dest={{ item.dest }} regexp='{{ item.regexp }}' line='{{ item.line }}' state=present"
  with_items:
    - { dest: /etc/php5/fpm/pool.d/www.conf, regexp: "^listen =", line: "listen = {{ blackroom_fastcgi_pass }}" }
    - { dest: /etc/php5/fpm/php.ini, regexp: '^;date.timezone', line: "date.timezone = {{ blackroom_php_timezone }}" }
    - { dest: /etc/php5/cli/php.ini, regexp: '^;date.timezone', line: "date.timezone = {{ blackroom_php_timezone }}" }
  notify:
    - restart php5-fpm
  tags: build
