---
- name: PreTasks | Execute lsb_release
  command: lsb_release -sc
  register: lsb
  tags:
    - init

- name: PreTasks | Update apt cache.
  apt: update_cache=yes
  tags:
    - apt
    - init

- name: PreTasks | Get software for Python-based control.
  apt: "pkg={{ item }} state=installed"
  with_items:
    - curl
    - python-apt
    - python-pycurl
    - software-properties-common
    - build-essential
    - apt-transport-https
    - vim
    - bash-completion
    - htop
    - rsync
  tags:
    - apt
    - init

- name: PreTasks | Add apt keys
  apt_key: url="{{ item }}" state="present"
  with_items:
    - "http://www.dotdeb.org/dotdeb.gpg" # dotdeb
  tags:
    - dotdeb
    - apt
    - init

- name: PreTasks | Create list files
  file: path=/etc/apt/sources.list.d/{{ item }} state=touch
  with_items:
    - "dotdeb.list"
  tags:
    - dotdeb
    - apt
    - init

- name: PreTasks | Add package repository
  lineinfile: dest="/etc/apt/sources.list.d/{{ item.dest }}" line="{{ item.line }}"
  with_items:
    - { dest: "dotdeb.list", line: "deb http://packages.dotdeb.org jessie all" }
    - { dest: "dotdeb.list", line: "deb-src http://packages.dotdeb.org jessie all" }
  tags:
    - dotdeb
    - apt
    - init

- name: PreTasks | Update apt cache.
  apt: update_cache=yes
  tags:
    - apt
    - init
