---
- name: Build | Install composer
  shell: curl -sS https://getcomposer.org/installer | php
  tags:
    - build
    - composer

- name: Build | Move composer.phar to composer
  command: mv composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
  tags:
    - build
    - composer

- name: Build | Make composer executable
  command: chmod a+x /usr/local/bin/composer
  tags:
    - build
    - composer

- name: Build | Add dependencies to locale profile
  lineinfile: "state=present dest=~/.bashrc
  regexp='^PATH=$PATH:./bin:./node_modules/.bin:~/.composer/vendor/bin:./vendor/bin$'
  line='PATH=$PATH:./bin:./node_modules/.bin:~/.composer/vendor/bin:./vendor/bin'"
  become: no
  tags:
    - build
    - composer
